---
- name: Add Logstash repo key
  rpm_key: key="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Enable Logstash repository
  template: src=logstash_repo.j2 dest=/etc/yum.repos.d/logstash.repo

- name: Install Logstash from repository
  yum: name={{ item }} state=latest
  with_items:
   - logstash
   - logstash-contrib

